### ISSUE TITLE
Explore the permissions of another user

### ISSUE THREAD

**Issue by juanjolainez** [machuga/authority-l4#29]
Hi! 

I haven't been able to see the permission of another user (for permission administration in a dashboard). How can I achieve that? 

I have tried this:

```
$user = User::find($id);
Authority::setCurrentUser($user);
foreach ($resources as $key => $resource) {
    foreach ($permissions as $key => $permission) {
        $permissionMatrix[$resource][$permission] = Authority::can($permission, $resource);
     }
}
```

and 

```
$user = User::find($id);
foreach ($resources as $key => $resource) {
    foreach ($permissions as $key => $permission) {
        $permissionMatrix[$resource][$permission] = Authority::can($permission, $resource, $user);
    }
}
```

and I only have the permissions of the user logged. How can I do that?

**Comment by machuga** [comment]
Hi! Sorry for delay I didn't get notified of this. You need to set the user prior to boot up otherwise authority already knows who you are.
